### PR TITLE
Feature/add messages properties files

### LINKED ISSUE #93: Add authn-messages.properties to the branding area
Add the authn-messages.properties to the branding area so the deploy-er can change the wording on the login page.

Ensure this file is copied from the assets area to the IdP's configuration - /opt/shibboleth/shibboleth-idp/current/messages

### LINKED ISSUE #94: Add consent-messages.properties to the branding area
Add the consent-messages.properties to the branding area so the deploy-er can change the wording on the consent page.

Ensure this file is copied from the assets area to the IdP's configuration - /opt/shibboleth/shibboleth-idp/current/messages

### LINKED ISSUE #95: Failed login messages give away information
The default error messages for a failed login attempt give away too much information. If the username is incorrect the user is told "The username you entered cannot be identified.". If a valid username is entered with an incorrect password the message "The password you entered was incorrect." is displayed.

This provides a means for someone to verify a username exists in the system.

Replace both messages with the common message "Unable to validate username or password".

This message appear in the authn-messages.properties file.

### PR DESCRIPTION
**Pull request by trsau**
This resolves #95, resolves #94 and resolves #93

### CODE REVIEW

**Comment by bradleybeddoes** [comment]
The changes proposed here look simple enough.

@trsau just wondering how you've tested these changes thus far

1. Installing a new instance?
1. Upgrading an existing instance?

If you've not had a chance to do one or the other do you feel it is necessary for me to undertake that before merge?

**Comment by trsau** [comment]
Hi Brad,

I have tested both and the new install works fine.

The update fails because the new file - authn-messages.properties
and consent-messages.properties are only added to the
assets/idp.example.edu.dist directory. They are only copied at bootstrap
time.

I have been thinking of ways to get new files and file that have updated
across from idp.example... to the assets for the deployed IdP. New file
should be fairly simple. File that already exist and need refreshing are
more difficult, particularly if they have been modified by the IdP admin. I
have some ideas but none very elegant yet,

Thanks,
Terry.



*Terry Smith* | Technical Manager | *Australian Access Federation Inc*
*Tel:*  +61 7 3138 2424 | *Mob:*  0414 692 424
*Email* t.smith@aaf.edu.au <http://twitter.com/ausaccessfed> | ORCID:
orcid.org/0000-0001-5971-4735
*Web:* http://www.aaf.edu.au <http://twitter.com/ausaccessfed> *| Support: *
http://support.aaf.edu.au
*Twitter:* http://twitter.com/ausaccessfed
*Mail: **PO Box 2104 | kelvin Grove  QLD  4059 | Australia*
                 <http://orcid.org/>
<http://www.aaf.edu.au>
                 Australian Consortium Lead

**Comment by bradleybeddoes** [comment]
@trsau if you're happy with that re: failure on upgrade, I can merge. Thought it might cause support jobs.

Has the requirement for the new files been documented somewhere? 

Do you want me to capture the details of this fault in a ticket? It seems to me that in the case of totally new files being needed in assets that the bootstrap process might be the best place to both check and copy from dist.

**Comment by trsau** [comment]
Hi Brad,

The bootstrap process is only run for the initial setup and successfully
copies all of the new files in assets. It is the update_idp.sh that needs
to do a little extra work when the -u (upgrade) option is selected.

I will create a new issue for this today or tomorrow. Can you hold off on
the merge till then.

Thanks,
Terry

*Terry Smith* | Technical Manager | *Australian Access Federation Inc*
*Tel:*  +61 7 3138 2424 | *Mob:*  0414 692 424
*Email* t.smith@aaf.edu.au <http://twitter.com/ausaccessfed> | ORCID:
orcid.org/0000-0001-5971-4735
*Web:* http://www.aaf.edu.au <http://twitter.com/ausaccessfed> *| Support: *
http://support.aaf.edu.au
*Twitter:* http://twitter.com/ausaccessfed
*Mail: **PO Box 2104 | kelvin Grove  QLD  4059 | Australia*
                 <http://orcid.org/>
<http://www.aaf.edu.au>
                 Australian Consortium Lead

**Comment by bradleybeddoes** [comment]
@trsau - apologies, I certainly should have referenced `update_idp.sh` and not `bootstrap.sh` in my previous comment.

Will hold merge until you're comfortable re: documentation/issue tracker. This also means I need to hold the merge of #97 as it depends on this PR.

**Comment by trsau** [comment]
Hi @bradleybeddoes PRs #96, #97, #101 and #102 are ready to go, i.e murge into develop/

**Pull request merged**
