### PR TITLE
Feature/software upgrade

### LINKED ISSUE #234: First MariaDB start up fails because /var/lib/mysql is not empty
They very first time MariaDB attempts to start on a server it tries to create an empty DB in /var/lib/mysql. If there are any files in this directory if fails and the database wont start.

The installer creates two sub directories before starting the DB, so it can never start until resolved manually. These directories don't seem to be required.

Move the config that creates the directories to after starting mysql, or remove altogether.

### PR DESCRIPTION
**Pull request by trsau**
Successfully installs latest versions of software.

close #234 #229

### CODE REVIEW

**Comment by trsau** [comment]
Hi Russell,

Not sure where binlog and tmp are coming from. I explicitly removed the config that created these directories from db.yml as it was causing mariadb to not start.

Terry.

**Comment by trsau** [comment]
Hi Russell,

Just successful ran this version of the installer and the mariadb started correctly. It did not create a binlog or tmp directory in /var/lib/mysql.

Did you change GIT_BRANCH to feature/software-upgrade in bootstrap.sh before running?

Thanks,
Terry

**Comment by rianniello** [comment]
My fault, didn't set the right branch.

Tested locally, I'm able to login to validator, everything looking good. 👍

**Comment by bradleybeddoes** [comment]
As usual I have to do @rianniello job for him...

**Pull request merged**
