### PR TITLE
Better migrate tool installation

### PR DESCRIPTION
**Pull request by rcaught**
- Doesn't store binary in the git repo
- Updates the jar if a newer version exists (based off file times)
- Manual download instructions

### CODE REVIEW

**Comment by rcaught** [comment]
Don't merge this yet @chrisjones120 (hence the unassign)

**Comment by chrisjones120** [comment]
> Don't merge this yet @chrisjones120 (hence the unassign)

Too keen

I like where this is going though, let me know when it's ready to go.

**Comment by bradleybeddoes** [comment]
FWIW GitHub now supports draft mode if you guys hadn't seen it https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by chrisjones120** [comment]
> FWIW GitHub now supports draft mode if you guys hadn't seen it https://github.blog/2019-02-14-introducing-draft-pull-requests/

That's neat, I didn't know about that

**Pull request closed without merging**
