### PR TITLE
Feature/shib 330

### LINKED ISSUE #186: Upgrade to Version 3.3.1 of Shibboleth
Current version is 3.2.1

### PR DESCRIPTION
**Pull request by trsau**
Update to Shibboleth version 3.3.1
Tested on new install and upgrade.

resolves #186 #187

### CODE REVIEW

**Comment by rianniello** [comment]
Will require updated versions / SHA checksums here: https://github.com/ausaccessfed/hosted-idp-ansible/pull/75.

**Comment by trsau** [comment]
The change to the version of aaf-shib-ext will be part of a separate feature / PR that I'm planning to do either later today or tomorrow.

**Comment by smangelsdorf** [comment]
@trsau: Does this mean that this PR breaks the installer until your next feature / PR is written?

If so, I'd advise waiting until the full set of changes is ready to be tested together.

**Comment by trsau** [comment]
No the PR does not break the installer. The installer with the changes in the PR works fine with the older version of the aaf-shib-ext library. As originally stated the in the PR the installer has been tested and functions correctly with both a new install and an upgrade from a previous install.

**Comment by rianniello** [comment]
Hmm, It may be good form to upgrade your aaf-shib-ext to the very latest, which is the proper release (which exists as a tag in source control — the other one doesn't)
```
 version: 1.1.1
 sha256sum: faf6de1f8be40ec3b3e9cab93ad8ee38a1de77dad51bef36358e28e8d6ae9116
```

**Comment by trsau** [comment]
Yes, I'm planning to, but wanted to do so in as separate feature/PR. First because the latest version wasn't ready when I issued the PR, and second I have a series of tests specific to the new version of the library that I want to do as the next step towards having alternatives for the underlying database.

**Comment by trsau** [comment]
Hi @rianniello I have added the 1.1.1 version of the aaf-shib-ext libraries config as requested. This may cause some issues with the possibility of multiple versions of the library being loaded which I will sort out in a subsequent feature.

**Comment by rianniello** [comment]
Have verified this locally on a fresh instance. Everything works as expected, I was able to login / use the services in my federation.

**Pull request merged**
